# Generated by Django 3.2.20 on 2025-04-02 16:57

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='Image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
