# Generated by Django 3.2.20 on 2025-04-02 17:00

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0002_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='gallery_image1',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_image2',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_image3',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='main_image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
