# Generated by Django 3.2.20 on 2025-04-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0003_alter_tour_group_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
