# Generated by Django 3.2.20 on 2025-04-02 17:09

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0004_auto_20250402_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='gallery_image1',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='gallery_image2',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='gallery_image3',
        ),
        migrations.AddField(
            model_name='tour',
            name='gallery_image1',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='gallery_image2',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='gallery_image3',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
