# Generated by Django 3.2.20 on 2025-04-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0005_auto_20250402_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='main_image',
        ),
    ]
