# Generated by Django 3.2.20 on 2025-04-14 23:37

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0005_auto_20250414_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrip',
            name='gallery_image1',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='gallery_image2',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daytrip',
            name='gallery_image3',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
