# Generated by Django 3.2.20 on 2025-04-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0008_daytrip_group_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytripbooking',
            name='optional_activities',
            field=models.ManyToManyField(blank=True, to='dede.OptionalActivity'),
        ),
    ]
