# Generated by Django 3.2.20 on 2025-04-07 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0008_alter_booking_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Number of people must be at least 1'), django.core.validators.MaxValueValidator(1000, message='Number of people cannot exceed 1000')]),
        ),
    ]
