# Generated by Django 3.2.20 on 2025-04-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0011_daytrip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrip',
            name='tour_type',
            field=models.CharField(choices=[('city', 'City Tour'), ('safari', 'Safari'), ('beach', 'Beach Holiday'), ('mountain', 'Mountain Trek'), ('cultural', 'Cultural Experience'), ('adventure', 'Adventure Tour'), ('wildlife', 'Wildlife Tour'), ('historical', 'Historical Tour'), ('food', 'Food & Culinary Tour'), ('religious', 'Religious Tour')], default='city', help_text='Type of tour', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('city', 'City Tour'), ('safari', 'Safari'), ('beach', 'Beach Holiday'), ('mountain', 'Mountain Trek'), ('cultural', 'Cultural Experience'), ('adventure', 'Adventure Tour'), ('wildlife', 'Wildlife Tour'), ('historical', 'Historical Tour'), ('food', 'Food & Culinary Tour'), ('religious', 'Religious Tour')], default='city', help_text='Type of tour', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='daytrip',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('none', 'One-time Trip'), ('weekend', 'Every Weekend'), ('saturday', 'Every Saturday'), ('sunday', 'Every Sunday')], default='none', help_text='Select if this is a recurring trip', max_length=20, null=True),
        ),
    ]
