# Generated by Django 3.2.20 on 2025-04-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0012_auto_20250425_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrip',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base price per person', max_digits=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base price per person', max_digits=10),
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_pax', models.PositiveIntegerField()),
                ('max_pax', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['min_pax'],
                'unique_together': {('min_pax', 'max_pax')},
            },
        ),
        migrations.AddField(
            model_name='daytrip',
            name='pricing_tiers',
            field=models.ManyToManyField(blank=True, related_name='day_trips', to='dede.PricingTier'),
        ),
        migrations.AddField(
            model_name='tour',
            name='pricing_tiers',
            field=models.ManyToManyField(blank=True, related_name='tours', to='dede.PricingTier'),
        ),
    ]
