# Generated by Django 3.2.20 on 2025-04-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0013_auto_20250425_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytrip',
            name='tour_type',
            field=models.CharField(choices=[('city', 'City Tour'), ('safari', 'Safari'), ('beach', 'Beach Holiday'), ('mountain', 'Mountain Trek'), ('cultural', 'Cultural Experience'), ('adventure', 'Adventure Tour'), ('wildlife', 'Wildlife Tour'), ('historical', 'Historical Tour'), ('food', 'Food & Culinary Tour'), ('religious', 'Religious Tour')], default='city tour', help_text='Type of tour', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('city', 'City Tour'), ('safari', 'Safari Experience'), ('beach', 'Beach Holiday'), ('mountain', 'Mountain Trek'), ('cultural', 'Cultural Experience'), ('adventure', 'Adventure Tour'), ('wildlife', 'Wildlife Tour'), ('historical', 'Historical Tour'), ('food', 'Food & Culinary Tour'), ('religious', 'Religious Tour')], default='city', help_text='Type of tour', max_length=20, null=True),
        ),
    ]
