# Generated by Django 3.2.20 on 2025-04-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0015_alter_tour_tour_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtier',
            name='max_pax',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='min_pax',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
