# Generated by Django 4.2.20 on 2025-05-30 15:00

from django.db import migrations


def migrate_price_to_base_price(apps, schema_editor):
    """Copy data from price field to base_price field for existing DayTrip records"""
    DayTrip = apps.get_model('dede', 'DayTrip')

    # Update all existing DayTrip records where base_price is 0 but price has a value
    for daytrip in DayTrip.objects.all():
        if hasattr(daytrip, 'price') and daytrip.price and (not hasattr(daytrip, 'base_price') or daytrip.base_price == 0):
            daytrip.base_price = daytrip.price
            daytrip.save()


def reverse_migrate_price_to_base_price(apps, schema_editor):
    """Reverse migration - copy base_price back to price field"""
    DayTrip = apps.get_model('dede', 'DayTrip')

    # Update all existing DayTrip records
    for daytrip in DayTrip.objects.all():
        if hasattr(daytrip, 'base_price') and daytrip.base_price:
            daytrip.price = daytrip.base_price
            daytrip.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0016_auto_20250425_0452'),
    ]

    operations = [
        migrations.RunPython(migrate_price_to_base_price, reverse_migrate_price_to_base_price),
        migrations.RemoveField(
            model_name='daytrip',
            name='price',
        ),
    ]
