# Generated by Django 3.2.20 on 2025-04-11 14:54

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
