# Generated by Django 3.2.20 on 2025-04-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'start_time']},
        ),
    ]
